import { Html, Head, Main, NextScript } from 'next/document';
import Script from 'next/script';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Custom Next.js Document that renders the root HTML structure and injects page-level scripts and runtime markers.
 *
 * Renders an <Html lang="en"> root with Head and body (suppresses hydration warnings), includes the application mount point,
 * injects a client-side script that sets `window.PP_VARIABLES.TEST` to "[Data Classification]", and emits Next.js runtime scripts.
 *
 * @returns The JSX element used as the server-rendered HTML document for the Next.js application.
 */
export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body suppressHydrationWarning>
        <Main />
        <Script
          id={'pp-variables'}
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.PP_VARIABLES = {
            TEST: '[Data Classification]',
          }`,
          }}
        ></Script>
        <NextScript />
      </body>
    </Html>
  );
}