import { Html, Head, Main, NextScript } from 'next/document';
import Script from 'next/script';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Custom Next.js Document component that renders the HTML skeleton, sets the page language to English, suppresses hydration warnings on the body, and injects a global `window.PP_VARIABLES` script.
 *
 * @returns A JSX element representing the server-rendered HTML document containing Head, Body (with `suppressHydrationWarning`), the application `Main`, an inline script that defines `window.PP_VARIABLES.TEST`, and Next.js runtime scripts.
 */
export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body suppressHydrationWarning>
        <Main />
        <Script
          id={'pp-variables'}
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.PP_VARIABLES = {
            TEST: '[Data Classification]',
          }`,
          }}
        ></Script>
        <NextScript />
      </body>
    </Html>
  );
}